GET http://localhost:3000/games HTTP/1.1
    
###

POST http://localhost:3000/games HTTP/1.1
Content-Type: application/json

{
    "title": "Dragon's Dogma: Dark Arisen",
    "description": "Em um incrível mundo aberto, Dragon’s Dogma: Dark Arisen apresenta um dos melhores sistemas de combate.  ",
    "price": "74.99",
    "img": "https://cdn.cloudflare.steamstatic.com/steam/apps/367500/header.jpg?t=1644282366"
}

###

DELETE http://localhost:3000/games/6 HTTP/1.1

###

PUT http://localhost:3000/games HTTP/1.1

{
    "id": 6
}